(base) matsuo@DESKTOP-1295BP3:~/library-demo$ docker compose -f docker-compose.prod.yml up --build -d
WARN[0000] /home/matsuo/library-demo/docker-compose.prod.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 0.1s (1/1) FINISHED                                                                         docker:default
 => [web internal] load build definition from Dockerfile.prod                                                      0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
failed to solve: failed to read dockerfile: open Dockerfile.prod: no such file or directory
